---------------------------------------------------
----Author: Leonardo Rodrigues Miranda Lins--------
----Language: SQL----------------------------------
----Tittle: DATABASE LOJA_dml----------------------
----Status: Doing----------------------------------
---------------------------------------------------

INSERT INTO CLI_CLIENTE VALUES (00001, 'JOAO CARLOS CABRERO', 'joao.ccabrero@email.com');
INSERT INTO CLI_CLIENTE VALUES (00002, 'VANESSA AMORIM SILVA', 'vanessa.amorimsilva23@email.com');
INSERT INTO CLI_CLIENTE VALUES (00003, 'PEDRO CARVALHO MUSSO', 'pedro.carvamusso@email.com');
INSERT INTO CLI_CLIENTE VALUES (00004, 'ANDREA DONIZETE PEREIRA', 'andrea_donipere@email.com');
INSERT INTO CLI_CLIENTE VALUES (00005, 'CAMILA BOATENG', 'camila.boateng@email.com');
INSERT INTO CLI_CLIENTE VALUES (00006, 'LUCAS PEDROSO GOUVEA', 'l.pedroso_gouvea@email.com');
INSERT INTO CLI_CLIENTE VALUES (00007, 'JOSEFA TULIO ALMEIDA', 'josefa_almeida@email.com');
INSERT INTO CLI_CLIENTE VALUES (00008, 'FLAVIO GETULIO BARBOSA', 'flavio.getu_barb@email.com');

INSERT INTO VEN_VENDEDOR VALUES (0001, 'CARLOS ATENCIO CABRERO', 'carlo.atencio@lojamail.com');
INSERT INTO VEN_VENDEDOR VALUES (0002, 'JESSICA MENDONCA LINS', 'jessica.lins@lojamail.com');
INSERT INTO VEN_VENDEDOR VALUES (0003, 'CARLA PETRUCIO', 'carla.petrucio@lojamail.com');

INSERT INTO PRD_PRODUTO VALUES (000001, 48, 'CAMISETA TITAURO G TAM', 'CAMISETA DA MARCA TITAURO TAMANHO G, NA COR CINZA');
INSERT INTO PRD_PRODUTO VALUES (000002, 48, 'CAMISETA TITAURO M TAM', 'CAMISETA DA MARCA TITAURO TAMANHO M, NA COR CINZA');
INSERT INTO PRD_PRODUTO VALUES (000003, 45, 'CAMISETA TITAURO P TAM', 'CAMISETA DA MARCA TITAURO TAMANHO P, NA COR PRETA');
INSERT INTO PRD_PRODUTO VALUES (000004, 90, 'CALCA LANDITO 44 TAM', 'CALCA JEANS DA MARCA TITAURO TAMANHO 44, NA COR AZUL MARINHO');
INSERT INTO PRD_PRODUTO VALUES (000005, 88, 'CALCA MATUCS 40 TAM', 'CALCA FEMININA DA MARCA MATUCS TAMANHO 40, NA COR BRANCA');
INSERT INTO PRD_PRODUTO VALUES (000006, 88, 'CALCA MATUCS 42 TAM', 'CALCA FEMININA DA MARCA MATUCS TAMANHO 40, NA COR BRANCA');
INSERT INTO PRD_PRODUTO VALUES (000007, 88, 'CALCA MATUCS 48 TAM', 'CALCA MASC DA MARCA MATUCS TAMANHO 48, NA COR BEJE');
INSERT INTO PRD_PRODUTO VALUES (000008, 95, 'SAPATO RIGIS 40 TAM', 'SAPATO DA RIGIS TAMANHO 40, NA COR PRETA');
INSERT INTO PRD_PRODUTO VALUES (000009, 95, 'SAPATO RIGIS 39 TAM', 'SAPATO DA RIGIS TAMANHO 39, NA COR PRETA');
INSERT INTO PRD_PRODUTO VALUES (000010, 95, 'SAPATO RIGIS 42 TAM', 'SAPATO DA RIGIS TAMANHO 42, NA COR PRETA');
INSERT INTO PRD_PRODUTO VALUES (000011, 95, 'SAPATO RIGIS 44 TAM', 'SAPATO DA RIGIS TAMANHO 44, NA COR PRETA');
